/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1ef0edff-28d8-4ccc-9676-8486b9761f3b",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "2347358ef20d491ea13d74c747179338",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
